### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by hllwd** [seracio/tennis-match#1]
What we have to represent : 

* a linear timeline of each point of a given tennis match 
  * each point is a square (or a circle), colorized by the winner's color of the point
* each opponent is represented on a side of this line
* a winning game, set or match is an arc encapsulating all its inner points, the arc is drawn on the side of the winner 
* the global difference of the total of points is a curve evolving after each point (the purpose of this vis will be to show how negligible this curve is)
* the weight of each point (how important it is)
* series (the max of won points straight, ...)

**Comment by hllwd** [comment]
We can also add : 

* the wingspan of a given game, for instance if player1 leads 40-0 but lose the game, the wingspan is 5 (which is the max wingspan for a game)

**Comment by hllwd** [comment]
The main question is how can we compute the `weight` of a point ? poke @nico-h

**Comment by hllwd** [comment]
Criteria to compute the weight of a point : 
* is the game important ? (no if it's a game from a 6-0 set for instance)
* Is it a break ?
* is the wingspan of the game important ?

**Comment by hllwd** [comment]
we should have a descendant process : what is an important set, game, and finally point

**Comment by Nico-h** [comment]
Every point is important because it's all about psychology in tennis :) But we can distinguish 3 types of point and giving them a weight. For instance: `neutral` - `important` - `crucial`

- Neutral => **1pt**
- Important => **3pts**
- Crucial => **5pts**

`neutral` point is when there are 2 points difference in a game => 30 - 0; the following point will make a 30 - 15 or 40 - 0 score wich as no big importance on the game. We can also set a limit where all points below 30 are neutral, or the firts 2 points are always neutral.

`important` point is when there is less than 2 points difference in a game => 30 - 30; the following point will produce a game point (or break). An other limit can be all points above 30 are important because very close to the end of the game.

`crucial` point is all point that lead to a game => Av - 40; the following point will give the game or come back to deuce, so the next point will be important

**Comment by hllwd** [comment]
We can also compute all the useless points of a player : all won points in a lost game

**Comment by Nico-h** [comment]
J'adore :+1:
